version: '3.8'

services:
#events --app
  events-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-app
    ports:
      - 7023:80
    restart: unless-stopped
    environment:
      SERVICE_NAME: events-app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./backend-api:/var/www/html
    networks:
      - events-app-network
    depends_on:
      - db_events_app

# database
  db_events_app:
    image: mysql:8.0.33
    container_name: db-events-app
    restart: unless-stopped
    tty: true
    ports:
    - 3373:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - dbdata_events:/var/lib/mysql
    networks:
      - events-app-network

      #php my admin
  phpmyadmin-events:
    container_name: events-phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 2340:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  dbdata_events:
    driver: local

networks:
  events-app-network:
    driver: bridge
