services:
  taic-reg-api:
    container_name: taic-reg-api
    build: .
    volumes:
      - ./backend-api:/var/www/html
    ports:
      - 6024:80

  taic-reg_mysql_db:
    container_name: taic-reg-ictc-db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: BeyondOrder24
      MYSQL_DATABASE: taic_reg_ictc
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - 3324:3306

  taic-reg_phpmyadmin:
    container_name: taic-reg-phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 6604:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data: