version: '3.8'

services:
#events --app
  events-stage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-stage
    ports:
      - 7023:80
    restart: unless-stopped
    environment:
      SERVICE_NAME: events-stage
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./backend-api:/var/www/html
    networks:
      - events-stage-network
    depends_on:
      - db_events_app

# database
  db_events_app:
    image: mysql:8.0.33
    container_name: db-events-stage
    restart: unless-stopped
    tty: true
    ports:
    - 3373:3306
    environment:
      MYSQL_DATABASE: event_app_db
      MYSQL_ROOT_PASSWORD: "robotUenice@34"
      MYSQL_PASSWORD: "InnovationK23"
      MYSQL_USER: 'ictc'
    volumes:
      - dbdata_stage_ems:/var/lib/mysql`
    networks:
      - events-stage-network

      #php my admin
  phpmyadmin-events:
    container_name: events-phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 2340:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  dbdata_stage_ems:
    driver: local

networks:
  events-stage-network:
    driver: bridge
