<?php

namespace App\Exports;

use App\Models\Bill;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;


class BillsExport implements FromCollection , WithHeadings{
    public function collection()
    {
        return Bill::select(
            "id",
            "conference_id",
            "user_id",
            "event_fee",
            "reference_no",
            "ReqId",
            "ack_id",
            "GrpBillId",
            "SpGrpCode",
            "phone_number",
            "payee_name",
            "billApproveBy",
            "customer_name",
            "name",
            "GfsCode",
            "tin_number",
            "callback_url",
            "bank_name",
            "account_number",
            "billGeneratedBy",
            "event_id",
            "amount",
            "remarks",
            "email",
            "grp_bill_id",
            "sp_grp_code",
            "cust_cntr_num",
            "entry_cnt",
            "sp_code",
            "bill_ctr_num",
            "psp_code",
            "psp_name",
            "trx_id",
            "pay_ref_id",
            "bill_amt",
            "paid_amt",
            "bill_pay_opt",
            "ccy",
            "currency",
            "rate",
            "coll_acc_num",
            "trx_dt_tm",
            "usd_pay_chnl",
            "trd_pty_trx_id",
            "qt_ref_id",
            "pyr_cell_num",
            "pyr_email",
            "pyr_name",
            "rsv1",
            "rsv2",
            "rsv3",
            "status",
            "paid_date",
            "status_code",
            "status_description",
            "callback_token",
            "bill_exp",
         )
             ->get();
    }
    public function headings(): array
    {
        return [
            "id",
            "conference_id",
            "user_id",
            "event_fee",
            "reference_no",
            "ReqId",
            "ack_id",
            "GrpBillId",
            "SpGrpCode",
            "phone_number",
            "payee_name",
            "billApproveBy",
            "customer_name",
            "name",
            "GfsCode",
            "tin_number",
            "callback_url",
            "bank_name",
            "account_number",
            "billGeneratedBy",
            "event_id",
            "amount",
            "remarks",
            "email",
            "grp_bill_id",
            "sp_grp_code",
            "cust_cntr_num",
            "entry_cnt",
            "sp_code",
            "bill_ctr_num",
            "psp_code",
            "psp_name",
            "trx_id",
            "pay_ref_id",
            "bill_amt",
            "paid_amt",
            "bill_pay_opt",
            "ccy",
            "currency",
            "rate",
            "coll_acc_num",
            "trx_dt_tm",
            "usd_pay_chnl",
            "trd_pty_trx_id",
            "qt_ref_id",
            "pyr_cell_num",
            "pyr_email",
            "pyr_name",
            "rsv1",
            "rsv2",
            "rsv3",
            "status",
            "paid_date",
            "status_code",
            "status_description",
            "callback_token",
            "bill_exp",
        ];
    }   
}


