version: '3'

services:
  events-app-api:
    build: .
    container_name: events-app-api
    working_dir: /var/www/html
    ports:
      - 6030:80
    volumes:
      - .:/var/www/html
      - /tmp:/tmp

    environment:
      APP_ENV: ${APP_ENV}  # Example environment variable
      APP_DEBUG: 'true'
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - events-ictc-app
    depends_on:
      - db-events-app
    healthcheck:
      test: ["CMD", "curl", "-f", "https://innovation.ictc.go.tz"]
      interval: 30s
      timeout: 10s
      retries: 3

  db-events-app:
    image: postgres:13.4
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 6032:${DB_PORT}
    networks:
      - events-ictc-app
    volumes:
      - pgproductiondata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgproductiondata:
    driver: local

networks:
  events-ictc-app:
    driver: bridge
