version: '3'

services:
  test-ems-api:
    build: .
    container_name: test-ems-api
    working_dir: /var/www/html
    ports:
      - 2020:80
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}  # Example environment variable
      APP_DEBUG: 'true'
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - testems-network
    depends_on:
      - test-ems-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  test-ems-db:
    image: postgres:13.4
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 2003:${DB_PORT}
    networks:
      - testems-network
    volumes:
      - test_ems_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  test_ems_pgdata:
    driver: local

networks:
  testems-network:
    driver: bridge
