services:
  events-test:
    container_name: events-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 2007:80

  events_test_db:
    container_name: event_test_db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: CallForOrder123455
      MYSQL_DATABASE: events_test_db
    volumes:
      - mysql_data_test_events:/var/lib/mysql
    ports:
    - 3307:3306

  events_test_phpmyadmin:
    container_name: event_app-phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 6207:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data_test_events: