services:
  events-app:
    container_name: events-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 6030:80

  event_app_db_01:
    container_name: events-app-db_01
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: CallForOrder123455
      MYSQL_DATABASE: events_ictc_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - 3397:3306

  event_app_phpmyadmin_01:
    container_name: event-app-phpmyadmin_01
    image: phpmyadmin:5.2.1
    ports:
      - 7334:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data: