// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/21/2024, 3:59:04 PM
const configMerger = require("/Users/apple/Projects/24TaicApp/Reg-app/site-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/apple/Projects/24TaicApp/Reg-app/site-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/plugins/**/*.{js,ts,mjs}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/composables/**/*.{js,ts,mjs}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/utils/**/*.{js,ts,mjs}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Projects/24TaicApp/Reg-app/site-app/app.config.{js,ts,mjs}"] }));

module.exports = config
