name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest #clarification

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Deployment Script
      run: ./deploy_api.sh


      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
