name: Deploy  Backend API On Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest #clarification

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Deployment Script
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.ICTCHOST}}
        username: ${{secrets.ICTCUSER}}
        key: ${{secrets.ICTCGITKEY}}
        script: ${{secrets.ICTC_STAGING_SCRIPT}}
